services:
  web:
    build: .
    container_name: scrapper-api
    ports:
      - "5000:5000"
    volumes:
      - ./static/pdf:/app/static/pdf
      - ./static/error:/app/static/error
      - ./logs:/app/logs
    env_file:
      - .env
    restart: unless-stopped