services:
  web:
    build: .
    container_name: scrapper-api
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./static/pdf:/pdf
      - ./logs:/app/logs
    restart: unless-stopped